### PR TITLE
[wip] ci: 👷update CI to populate with secrets

### PR DESCRIPTION
**Pull request by DistributedDoge**
Doing a bit of testing in production to see if there is an easy solution to #47.

### CODE REVIEW

**Comment by DistributedDoge** [comment]
Whole point of making this commit was to trigger modified `CI workflow` on your branch and see if `public_tx_registry` model would be supplied with COVALENT_API_KEY secret, but it looks like Github is being a bit careful here.

**Comment by davidgasquez** [comment]
Huh! I don't even have the option to force CI. Seems [there are no checks](https://github.com/davidgasquez/gitcoin-grants-data-portal/pull/49/checks)!

**Review by davidgasquez — COMMENTED** [review]
Should we go ahead, merge, and learn on prod? :shrug:

**Comment by DistributedDoge** [comment]
Worst thing this can do is break CI workflow - which ATM already doesn't work for contributors, let's try it and see what happens after I make a new PR.

**Pull request merged**
